// auth

// cart
const CART_ACTION_START = 'CART_ACTION_START';
const CART_ACTION_FAIL = 'CART_ACTION_FAIL';
const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
const INCREASE_PRODUCT_COUNT_OF_CART = 'INCREASE_PRODUCT_COUNT_OF_CART';
const DECREASE_PRODUCT_COUNT_OF_CART = 'DECREASE_PRODUCT_COUNT_OF_CART';


// category
const CATEGORY_ACTION_START = 'CATEGORY_ACTION_START';
const CATEGORY_ACTION_FAIL = 'CATEGORY_ACTION_FAIL';
const ADD_CATEGORY = 'ADD_CATEGORY';
const EDIT_CATEGORY = 'EDIT_CATEGORY';
const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

// filter

// order
const PLACE_ORDER = 'PLACE_ORDER';


// product
const PRODUCT_ACTION_START = 'PRODUCT_ACTION_START';
const PRODUCT_ACTION_FAIL = 'PRODUCT_ACTION_FAIL';
const ADD_PRODUCT = 'ADD_PRODUCT';
const EDIT_PRODUCT = 'EDIT_PRODUCT';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const RATE_PRODUCT = 'RATE_PRODUCT';
const INCREASE_PRODUCT_COUNT = 'INCREASE_PRODUCT_COUNT';
const DECREASE_PRODUCT_COUNT = 'DECREASE_PRODUCT_COUNT';

// subcategory
const SUBCATEGORY_ACTION_START = 'SUBCATEGORY_ACTION_START';
const SUBCATEGORY_ACTION_FAIL = 'SUBCATEGORY_ACTION_FAIL';
const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
const EDIT_SUBCATEGORY = 'EDIT_SUBCATEGORY';
const REMOVE_SUBCATEGORY = 'REMOVE_SUBCATEGORY';

// user
const USER_ACTION_START = 'USER_ACTION_START';
const USER_ACTION_FAIL = 'USER_ACTION_FAIL';
const ADD_USER = 'ADD_USER';
const EDIT_USER = 'EDIT_USER';
const REMOVE_USER = 'REMOVE_USER';
const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
const EDIT_USER_ADDRESS = 'EDIT_USER_ADDRESS';
const REMOVE_USER_ADDRESS = 'REMOVE_USER_ADDRESS';
